// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnjH8x__jmtPnFGYyWiSEP5zdU_ylFE8Y',
    appId: '1:1040807343835:web:903c83a56b432dded47efe',
    messagingSenderId: '1040807343835',
    projectId: 'locker-39830',
    authDomain: 'locker-39830.firebaseapp.com',
    storageBucket: 'locker-39830.firebasestorage.app',
    measurementId: 'G-LFTTZN1ECW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0f-JDbU3-01XlwshqIcXdO8AXtJ2Pog0',
    appId: '1:1040807343835:android:b2ad54461fae5e7bd47efe',
    messagingSenderId: '1040807343835',
    projectId: 'locker-39830',
    storageBucket: 'locker-39830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoLXEOfQs4mqis8NqKPofCYhjiUJ8Jh0g',
    appId: '1:1040807343835:ios:898ab79d33656384d47efe',
    messagingSenderId: '1040807343835',
    projectId: 'locker-39830',
    storageBucket: 'locker-39830.firebasestorage.app',
    iosBundleId: 'com.example.locker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoLXEOfQs4mqis8NqKPofCYhjiUJ8Jh0g',
    appId: '1:1040807343835:ios:898ab79d33656384d47efe',
    messagingSenderId: '1040807343835',
    projectId: 'locker-39830',
    storageBucket: 'locker-39830.firebasestorage.app',
    iosBundleId: 'com.example.locker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnjH8x__jmtPnFGYyWiSEP5zdU_ylFE8Y',
    appId: '1:1040807343835:web:0f4a250dac66290ad47efe',
    messagingSenderId: '1040807343835',
    projectId: 'locker-39830',
    authDomain: 'locker-39830.firebaseapp.com',
    storageBucket: 'locker-39830.firebasestorage.app',
    measurementId: 'G-LJV2Y265S2',
  );
}
